### ISSUE TITLE
LaTeX in some tables isn't rendering correctly

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#143] opened 2019-01-22 18:36 UTC
For certain problems, the math notation within a table, or even in certain cells isn't rendering properly on the OL-WW site.  E.g.:

WW: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/Functions_-_Difference_Quotient/4/?key=VYKlNLYNiiOn8eSkR5GcGwItwPMTjs52&effectiveUser=student1&user=student1

OL-WW: http://openlabdev.org/webwork-playground/#:problemId=local2/setDifference_Quotient/diff-quot-rational.pg:questionId=11801

WW
![screen shot 2019-01-22 at 1 31 19 pm](https://user-images.githubusercontent.com/7189824/51557212-4543df80-1e4a-11e9-8831-26be03d4cd7c.png)

OL-WW
![screen shot 2019-01-22 at 1 31 10 pm](https://user-images.githubusercontent.com/7189824/51557206-3fe69500-1e4a-11e9-848b-9093947b6345.png)

Let me know if you need any other examples, thanks!

**Comment by boonebgorges** [comment] 2019-01-22 20:09
Thanks for the details, Bree. This appears to be a duplicate of #133, where the source content was written using backticks as LaTeX delimiters within the columns. See especially https://github.com/livinglab/webwork-for-wordpress/issues/133#issuecomment-424502219 and follow-up comments. Perhaps @drdrew42 can chime in and confirm that backtick delimiters will be replaced in production content?

**Comment by boonebgorges** [comment] 2019-01-24 15:14
Tentatively closing based on earlier discussion regarding backticks. If this comes up in production, and we discover that we need to add backticks as a TeX delimiter in at least some contexts, we can explore at that time.

**Closed by boonebgorges** 2019-01-24 15:14 UTC
